# Generated by Django 2.0.1 on 2018-01-12 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitenum1', '0002_auto_20180111_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guestbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_idx', models.IntegerField(blank=True, null=True)),
                ('guest_memo', models.TextField(blank=True, null=True)),
                ('guest_name', models.CharField(blank=True, max_length=50, null=True)),
                ('guest_ip', models.CharField(blank=True, max_length=50, null=True)),
                ('guest_regdate', models.DateField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'guestbook',
            },
        ),
    ]
